In [7]:
import numpy as np

In [2]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns?

In [5]:
arr=np.random.randint(1,101,(3,3))
arr

array([[31, 86, 45],
       [63, 73, 76],
       [54, 96,  7]])

In [6]:
#Interchange Rows and col:
arr.T

array([[31, 63, 54],
       [86, 73, 96],
       [45, 76,  7]])

In [7]:
#Q2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?

In [9]:
arr=np.array([1,4,2,6,8,9,11,12,3,10])
arr

array([ 1,  4,  2,  6,  8,  9, 11, 12,  3, 10])

In [10]:
np.reshape(arr,(2,5))    #Reshaping array to 2*5

array([[ 1,  4,  2,  6,  8],
       [ 9, 11, 12,  3, 10]])

In [11]:
np.reshape(arr,(5,2))     #Reshape array to 5*2

array([[ 1,  4],
       [ 2,  6],
       [ 8,  9],
       [11, 12],
       [ 3, 10]])

In [12]:
#Q3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array?

In [60]:
arr=np.random.rand(4,4)
arr

array([[0.02943506, 0.80475581, 0.88664878, 0.6500709 ],
       [0.90212312, 0.19954705, 0.40880769, 0.87625167],
       [0.71783759, 0.33042593, 0.05582851, 0.51024899],
       [0.00189942, 0.04029046, 0.3394669 , 0.42257405]])

In [70]:
arr2=np.zeros((6,6))
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [76]:
arr2[1:5,1:5]+=arr

In [67]:
#Q4 Using NumPy, create an array of integers from 10 to 60 with a step of 5?

In [28]:
arr=np.arange(10,61,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [29]:
#Q5  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element?

In [31]:
arrs=["python","numpy","pandas"]
np.char.capitalize(arrs)   #To capitalize all str characters of array

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [33]:
np.char.upper(arrs)    #Conversion to Upper Case

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [34]:
np.char.title(arrs)     #Conversion to Title

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [35]:
# Q6 Generate a NumPy array of words. Insert a space between each character of every word in the array?

In [29]:
x=np.array(["pwskills","data"])

In [36]:
lis=[' '.join(x[0]),' '.join(x[1])]
x=np.array(lis)
x

array(['p w s k i l l s', 'd a t a'], dtype='<U15')

In [43]:
# Q7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division?

In [45]:
arr1=np.random.randint(1,5,(2,2))
arr2=np.random.randint(5,9,(2,2))

In [46]:
arr1

array([[4, 1],
       [1, 4]])

In [47]:
arr2

array([[8, 5],
       [6, 7]])

In [48]:
np.add(arr1,arr2)    #Element wise addition

array([[12,  6],
       [ 7, 11]])

In [49]:
np.subtract(arr1,arr2)   #Element wise Subtraction

array([[-4, -4],
       [-5, -3]])

In [50]:
np.multiply(arr1,arr2)    #Multiplication

array([[32,  5],
       [ 6, 28]])

In [51]:
np.divide(arr1,arr2)    #Division

array([[0.5       , 0.2       ],
       [0.16666667, 0.57142857]])

In [52]:
#Q8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements?

In [55]:
arr=np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
arr.diagonal()

array([1., 1., 1., 1., 1.])

In [57]:
#Q9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array?

In [4]:
arr=np.random.randint(0,1000,100)
lis=list(arr)

In [12]:
prime=[]
for i in lis:
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            prime.append(i)
arr=np.array(prime)
arr

array([739,  19, 457, 937, 109, 271, 211, 593, 227, 457, 593, 211, 419,
       523, 439, 353, 823, 503, 607, 641])

In [14]:
#Q10 Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages?

In [20]:
temp=np.random.randint(21,36,31)
temp

array([32, 21, 34, 27, 28, 28, 34, 26, 24, 34, 30, 28, 35, 35, 34, 24, 34,
       30, 35, 32, 22, 32, 29, 24, 24, 23, 21, 25, 35, 35, 32])

In [23]:
week1=temp[0:8]
week2=temp[8:15]
week3=temp[15:22]
week[

array([32, 21, 34, 27, 28, 28, 34, 26])

In [1]:
#Theory Questions

In [2]:
#Q1  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [4]:
ans='''Numpy is one librabry present in python made by using C language to make calculation more faster\n
It is Fast beacuse it store data in form of array which store only Homogeneous Data which makes it more fast as compared to normal mathematical operations in python.'''
print(ans)

Numpy is one librabry present in python made by using C language to make calculation more faster

It is Fast beacuse it store data in form of array which store only Homogeneous Data which makes it more fast as compared to normal mathematical operations in python.


In [5]:
#Q2  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [10]:
data=np.random.randint(1,5,10)
data

array([3, 2, 1, 4, 4, 2, 3, 1, 3, 2])

In [14]:
np.average(data)   #Mostly used to find central data for small data

2.5

In [15]:
data2=np.random.rand(1,10,1000)
np.mean(data2)         #Mostly used for large data in statistical terminology

0.5015121893951089

In [17]:
# Q3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays?

In [24]:
lis=[1,2,3,4,5]
np.flipud(lis)  #To reverse 1-D array data

array([5, 4, 3, 2, 1])

In [25]:
arr=np.array(lis)
arr[::-1]      #2nd way to reverse array in 1-D

array([5, 4, 3, 2, 1])

In [27]:
#For 2-D array
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.flip(arr2,axis=0)     #Revrse row wise only

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [30]:
np.flip(arr2,axis=1)     #Reverse columnn wise

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [31]:
np.flip(arr2)      #Reverse in both ways

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [33]:
#Q4 How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance?

In [43]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [46]:
print('''So, in above example dtype of arr is int\nwe should choose data type wisely because it affects memory consumption and computational speed of data''')

So, in above example dtype of arr is int
we should choose data type wisely because it affects memory consumption and computational speed of data


In [47]:
#Q5  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [49]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
np.ndim(arr)  #This show Dimension of array

2

In [50]:
arr2=np.array([[[1,2,3,4],[5,6,7,8],[1,3,5,7]]])
np.ndim(arr2)

3

In [51]:
'''ndim is used to get information about dimension of array which is not present in normal list function of python
With its help, we can store any dimension data in form of array like 1D, 2D, 3D----nD.'''

'ndim is used to get information about dimension of array which is not present in normal list function of python\nWith its help, we can store any dimension data in form of array like 1D, 2D, 3D----nD.'

In [52]:
#Q6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations?

In [64]:
#Numpy have very high speed over list because it stores homogeneous data and list store any data type
import time
start=time.perf_counter()
arr=np.arange(50000)
print(np.sum(arr))
end=time.perf_counter()
print(end-start)

1249975000
0.0007226869929581881


In [63]:
#On the other hand for list
start=time.perf_counter()
lis=list(range(50000))
sum=0
for i in lis:
    sum=sum+i
print(sum)
end=time.perf_counter()
print(end-start)

1249975000
0.009954010136425495


In [65]:
ans='''We can see the difference in time for both calculations, numpy is way more faster than list calculation\n And if same calculation is in crores, then time difference become more visible'''
print(ans)

We can see the difference in time for both calculations, numpy is way more faster than list calculation
 And if same calculation is in crores, then time difference become more visible


In [66]:
#Q7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output?

In [70]:
arr=np.array([1,2,3,4,5])
np.vstack(arr)     #Used to arrange data in vertical position

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [73]:
np.hstack(np.array([[1,2,3],[4,5,6]]))   #2D data is converted to hstack that in form of horizontal array

array([1, 2, 3, 4, 5, 6])

In [74]:
#Q8  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions?

In [75]:
#Both functions are used similar to roll function present in numpy, They are used to flip rows, col in 2D, 3d Arrays
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
#fliplr function= flip left right column wise, it flip arr form left to righ columnwise
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [77]:
#flipud= flip-up-down i.e it flip arr form up to down row-wise
np.flipud(arr)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [78]:
#Q9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [88]:
#One of the most useful function to split array even if it is not evenly divided. 
#Very Important to produce Sub-arrays
arr=np.array([[1,2,3],[4,5,6]])
np.split(arr,3,axis=1)   #This is split function, mostly used to create sub-arrays but it is not able to split unequal array

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [90]:
#So, to split unequal array divisions we use array.split() function 
arr=np.array([[1,2,3],[4,5,6]])
np.array_split(arr,4,axis=1)   #It is able to construct subarray of 2d array into 4 different sub arrays 

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]]),
 array([], shape=(2, 0), dtype=int64)]

In [91]:
#Q10  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [93]:
#These are one of the most powerful tools in numpy which makes its speed very fast 
#Vectorization= It is used when we perform operation on array, then instead of going to each element by using loop, vactorization select whole array at a time and perform specified operation at a time to all elements
arrv=np.array([[1,2,3],[4,5,6],[7,8,9]])
arrv

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
#Vectorization 
arrv**2   #All elements will be selected automatically and the specified operation of power is performed 

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [95]:
#If vectorization is not present, then we have to get to each element from loop and then have to perform operation by using function

In [96]:
#Broadcasting= This is also one of most powerful function which basically help in adding two arrays even if there dimensions is different
arr1=np.array([1,2,3,4])  #size=1
arr2=np.array([[1],[2],[3],[4]])  #size=4*1
arr1+arr2

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [97]:
#Above operation is only possible because of broadcasting, it convert arr1 to 4*4 array by strteching 
#its dimension along row wise, similarly it stretches arr2 column wise to make both 4*4
#And then give the result by making them compatible and then adding